all : DOS DPMI

DOS: SYSTEM2.TPU WINCB.TPU STRBIN.TPU ARGS.TPU DBM.TPU DBB.TPU RC4.TPU ANSI.TPU QSORT.TPU STR.TPU ARRAYS.TPU KMINPUT.TPU
DPMI: SYSTEM2.TPP WINCB.TPP STRBIN.TPP ARGS.TPP DBM.TPP DBB.TPP RC4.TPP ANSI.TPP QSORT.TPP STR.TPP ARRAYS.TPP KMINPUT.TPP

SYSTEM2.TPU: SYSTEM2.PAS EXMS.PAS
        tpc /m SYSTEM2.PAS

SYSTEM2.TPP: SYSTEM2.PAS
        bpc /m /cp SYSTEM2.PAS

QSORT.TPU: QSORT.PAS
        tpc /m QSORT.PAS

QSORT.TPP: QSORT.PAS
        bpc /m /cp QSORT.PAS

WINCB.TPU: WINCB.PAS
        tpc /m WINCB.PAS

WINCB.TPP: WINCB.PAS
        bpc /m /cp WINCB.PAS

ARGS.TPU: ARGS.PAS
        tpc /m ARGS.PAS

ARGS.TPP: ARGS.PAS
        bpc /m /cp ARGS.PAS

ANSI.TPU: ANSI.PAS
        tpc /m ANSI.PAS

ANSI.TPP: ANSI.PAS
        bpc /m /cp ANSI.PAS

DBM.TPU: DBM.PAS SYSTEM2.PAS
        tpc /m DBM.PAS

DBM.TPP: DBM.PAS SYSTEM2.PAS
        bpc /m /cp DBM.PAS

RC4.TPU: RC4.PAS
        tpc /m RC4.PAS
RC4.TPP: RC4.PAS
        bpc /m /cp RC4.PAS

STR.TPU: STR.PAS
        tpc /m STR.PAS
STR.TPP: STR.PAS
        bpc /m /cp STR.PAS

STRBIN.TPU: STRBIN.PAS
        tpc /m STRBIN.PAS
STRBIN.TPP: STRBIN.PAS
        bpc /m /cp STRBIN.PAS

ARRAYS.TPU: ARRAYS.PAS STR.TPU
        tpc /m ARRAYS.PAS
ARRAYS.TPP: ARRAYS.PAS STR.TPP
        bpc /m /cp ARRAYS.PAS

KMINPUT.TPU: KMINPUT.PAS
        tpc /m KMINPUT.PAS
KMINPUT.TPP: KMINPUT.PAS
        bpc /m /cp KMINPUT.PAS

DBB.TPU: DBB.PAS SYSTEM2.PAS
        tpc /m DBB.PAS
DBB.TPP: DBB.PAS SYSTEM2.PAS
        bpc /m /cp DBB.PAS

clean:
        del *.TPU
        del *.TPP
        del *.BAK
install: all
        copy *.tpu ..\TPU\
        copy *.tpp ..\TPU\

